// <auto-generated />
namespace EntityCodeFirstExamples.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Customers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Customers));
        
        string IMigrationMetadata.Id
        {
            get { return "202203061427047_Customers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
